### ISSUE TITLE
Is this compatible with the Xavier NX too

### ISSUE THREAD

**Issue by danriches** [InES-HPMM/Lontium_lt6911uxc#1]
Hi,
I have two dev boards that have the LT6911UXC on board and would like to get this working on a Jetson Xavier NX, does this driver work with the NX or does it need the references changing from the AGX or TX2?

Kind Regards,

Dan

**Comment by alegroo** [comment]
Dear @danriches,

We did not test the driver with a Xavier NX but are convinced that it would work. No platform specific code is included in the driver.  
What you will need to do is to modify the addresses and properties of VI/CSI/NVCSI and I2C nodes in the device tree according to your hardware.

Please notify us if you experience any issues in porting to the NX or TX2

Best regards,
Alex

**Comment by srisurya97** [comment]
can i use rockchip dtsi file with this? I cant find dtsi for this lontium in dts.

**Comment by Launchpad-McQ** [comment]
> Hi,
> I have two dev boards that have the LT6911UXC on board and would like to get this working on a Jetson Xavier NX, does this driver work with the NX or does it need the references changing from the AGX or TX2?
> 
> Kind Regards,
> 
> Dan

Did you make it work with Jetson NX? If so it would be very nice if you could you share what you had to change or share your fork.

Best,

**Comment by danriches** [comment]
Hi Launchpad, I decided to use the TC358840 from Toshiba for 4kp30 as the board I had with the Lontium part on it would have had to be modified heavily first and as the support I've had from Toshiba has been great I thought I'd stick with them instead. However, saying that I do plan to take another look at getting it going just so we have an alternative if required. When I do I'll try to remember to post my findings on here or on my own github (new repo will be created). Don't hold out for it though as I may not have the time to do it... If you have a basic PCB design for this part that you can share I can order a couple from JLCPCB and test it again and report back as that's really the main thing stopping me with the Lontium part at the moment...

Cheers, Dan
