### ISSUE TITLE
INT pin connection to Xavier NX

### ISSUE THREAD

**Issue by danriches** [InES-HPMM/Lontium_lt6911uxc#5]
Hi, Now the driver is included in the latest release of JetPack, where can I find the definitions for the interrupt pin? My hardware spec has changed and we have to use the Lontium part, Lontium have been very helpful and i've programmed the part and have responses over i2c to test the basics. However I haven't connected up the interrupt pin to the Xavier NX and quite frankly don't know where exactly to look for the pin def. Can anyone shed any light on this please? Is it in the dts files and if so which one?

For reference I'm using the Auvidea JNX30, and yes Auvidea are useless at being of any help at all. I won't be using them again either same as another user has posted!!

Thanks ever so much, 
Dan

**Comment by alegroo** [comment]
Hi Dan,
Here is an example of the devicetree node [lt6911uxc.txt](https://github.com/InES-HPMM/Lontium_lt6911uxc/blob/main/lt6911uxc.txt). On [line 27 ](https://github.com/InES-HPMM/Lontium_lt6911uxc/blob/372cc2586fdb419ef4c962d738c769b1afb2e3b2/lt6911uxc.txt#L27) is the definition of the interrupt pin

**Comment by danriches** [comment]
Hi,

I can see from the file that gpio H,3 and gpio P,0 are used for reset and interrupt respectively, now going through the pinmux spreadsheet I can see GPIO3_PP.00 is used for the CAM0_CLK so I can re-assign that one. What about reset though as I can't seem to find a reference to GPIO3_PH.03 anywhere, is there another I can use or can I just define it?

Sorry I'm really new to the device tree so I'm still learning about it and any help is greatly appreciated.

Kind Regards, Dan

**Comment by alegroo** [comment]
Hi,
You need to know the schematics of the baseboard and Lontium module. With this information, you can figure out which pin of the Xavier NX the Lontium interrupt and the reset Pins are connected (maybe only the interrupt is connected). With the help of the pinmux you can figure out which pin you need to use. You can just overwrite this value in your devicetree. Unfortunately, we have no NX platform available and tested our driver with custom hardware.
PS: If the reset pin is not connected to the lontium module, choose a free GPIO
